#!/bin/csh -f

# script for scanning urls of current modis products

# Prof. P. Lewis, UCL
# Oct 20 2013
# email: p.lewis@ucl.ac.uk


# Zat is the name of a friendly robot in a John Wyndham
# story, The Lost Machine (Amazing Stories, April 1932).
# 
set here = `pwd`

set server = 'ftp://n4ftl01u.ecs.nasa.gov/'
@ y = 2000
while ( $y <= 2013 )
  rm -f files/data/robot_snow.$y.txt
  foreach m (`awk 'BEGIN{for(i=1;i<=12;i++)printf("%02d ",i)}'`)
    echo $y $m
    $here/python/ftp-snow $y $m |  grep hdf | awk '{print w $NF}' w=$server >> files/data/robot_snow.$y.txt
  end
  @ y++
end


