#!/bin/csh -f

ipython nbconvert f1_index.ipynb
foreach i (*html)
  sed < $i 's/ipynb/html/g' > x ; mv x $i
  sed < $i 's/http:\/\/nbviewer.ipython.org\/urls\/raw.github.com\/profLewis\/geogg122\/master/../g' > x;mv x $i
end

git add *
git commit -m 'fixed html links again Ch3'
git push origin master

